[env]
TERM = "screen-256color"

[window]
decorations = "none"
# opacity = 0.9

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "fish"

[font]
size = 10

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Space"
mods = "Control"
action = "ToggleViMode"

# Gruvbox dark palette (medium contrast)
[colors.primary]
background = "#282828"
foreground = "#EBDBB2"

[colors.cursor]
text = "#282828"
cursor = "#EBDBB2"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#FE8019"

[colors.selection]
text = "CellForeground"
background = "#504945"

[colors.normal]
black = "#282828"
red = "#CC241D"
green = "#98971A"
yellow = "#D79921"
blue = "#458588"
magenta = "#B16286"
cyan = "#689D6A"
white = "#A89984"

[colors.bright]
black = "#928374"
red = "#FB4934"
green = "#B8BB26"
yellow = "#FABD2F"
blue = "#83A598"
magenta = "#D3869B"
cyan = "#8EC07C"
white = "#EBDBB2"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
